language: node_js
node_js:
  - "9"
env:
  - CXX=clang
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - g++-4.8
      - llvm-3.6
      - libstdc++-4.9-dev
      - llvm-3.6-dev
      - clang-3.6
compiler: clang
branches:
  only:
    - master
cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.node-gyp/9.5.0
    - $HOME/.npm
notifications:
  email: false
node_js:
  - node
script:
  - npm run test && npm run build
after_success:
  - npm run report-coverage
